### ISSUE TITLE
I got a problem building camkes on ubuntu

### ISSUE THREAD

**Issue by AlanYiNew** [seL4/camkes-manifest#1]
Everytime when i make, there is always an error saying xxxx.cdl : unxpected 'L' but hexadecimal digit or ':' and I have to go into the cdl file to manually delete the 'L' letter. Where can find the script that generate those cdl files. I don't want to delete those L manually every time

`WARNING: Installation path /home/alan/camkes-project/projects/capdl/capDL-tool not found on the PATH environment variable
make: Leaving directory '/home/alan/camkes-project/projects/capdl/capDL-tool'
[parse-capDL] done.
[cpio-strip] building...
 [CC] cpio-strip
[cpio-strip] done.
[apps/capdl-loader-experimental] building...
 [HEADERS]
 [STAGE] debug.h
 [STAGE] capdl_spec.h
 [STAGE] capdl.h
 [STAGE] autoconf.h
 [GEN] capdl_spec.c
parse-capDL: "/home/alan/camkes-project/build/arm/imx31/simple/simple.cdl" (line 119, column 4):
unexpected "L"
expecting hexadecimal digit or ":"
CallStack (from HasCallStack):
  error, called at Main.hs:130:19 in main:Main
/home/alan/camkes-project/apps/capdl-loader-experimental/Makefile:50: recipe for target '/home/alan/camkes-project/build/arm/imx31/capdl-loader-experimental/src/capdl_spec.c' failed
make[1]: *** [/home/alan/camkes-project/build/arm/imx31/capdl-loader-experimental/src/capdl_spec.c] Error 1
tools/common/project.mk:330: recipe for target 'capdl-loader-experimental' failed
make: *** [capdl-loader-experimental] Error 2
`

**Comment by kent-mcleod** [comment]
This could be due to an old unspecified build-system problem.  If it still occurs on a recent Camkes checkout, feel free to reopen this issue.
