### ISSUE TITLE
Ninja build error - Camkes Tutorial 

### ISSUE THREAD

**Issue by jhu960213** [seL4/camkes-manifest#8]
Hello,

I'm following along the tutorial specified here: https://docs.sel4.systems/projects/camkes/. After invoking:
- ../init-build.sh -DPLATFORM=sabre -DAARCH32=1 -DCAMKES_APP=adder -DSIMULATION=1
- ninja

I'm getting this build error, please see attached. I'm not sure how to go about fixing this dependency issue. 
![Screenshot from 2021-03-31 14-58-53](https://user-images.githubusercontent.com/20133323/113196659-c28ceb00-9231-11eb-8fb3-513599af9305.png)

I'm running ubantu 20.04 TS and have installed all the base sel4 dependencies, etc. 

Best,
J.H

**Comment by oliver-wm** [comment]
Hey @jhu960213 can you test you have gcc installed correctly? Looks like `/home/linuxbrew/.linuxbrew/bin/gcc` could be a dead symlink?

**Comment by axel-h** [comment]
Closing, there was no follow-up from @jhu960213. It should work when using the docker container.
